version: '2'
services:
  web:
    build: .
    environment:
      - DOGSTATSD_HOST=dogstatsd
    ports:
      - 8080:8080
  dogstatsd:
    image: datadog/docker-dd-agent:latest-dogstatsd
    environment:
      - API_KEY=${DATADOG_API_KEY}
