apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sendgrid2datadog
  namespace: sendgrid2datadog
  labels:
    name: sendgrid2datadog
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: sendgrid2datadog
      labels:
        name: sendgrid2datadog
        role: web
    spec:
      containers:
      - image: quay.io/dtan4/sendgrid2datadog:latest
        name: sendgrid2datadog
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
        envFrom:
        - secretRef:
            name: sendgrid2datadog
      - image: datadog/docker-dd-agent:latest-dogstatsd
        name: dogstatsd
        ports:
        - containerPort: 8125
        envFrom:
        - secretRef:
            name: dd-agent
