apiVersion: v1
kind: Service
metadata:
  name: sendgrid2datadog
  namespace: sendgrid2datadog
  labels:
    name: sendgrid2datadog
    role: web
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    name: sendgrid2datadog
    role: web
  type: LoadBalancer
